- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: documentation
  color: 0075ca
  description: Documentation improvements
- name: question
  color: d876e3
  description: Usage question
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: help wanted
  color: 008672
  description: Extra attention is needed
- name: priority: high
  color: b60205
  description: High priority
- name: priority: medium
  color: fbca04
  description: Medium priority
- name: priority: low
  color: 0e8a16
  description: Low priority
