name: Bug report
description: Report a bug or regression
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened? Include expected vs actual.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps or a short repro snippet.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs, stack traces, or screenshots.
      render: shell
    validations:
      required: false
  - type: input
    id: package-version
    attributes:
      label: Package version
      placeholder: 1.2.3
    validations:
      required: true
  - type: input
    id: sdk-version
    attributes:
      label: SDK version
      description: Output of `dart --version` or `flutter --version`.
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: OS / Platform
      placeholder: macOS 14, Ubuntu 22.04, Windows 11
    validations:
      required: true
  - type: dropdown
    id: reproducible
    attributes:
      label: Reproducibility
      options:
        - Always
        - Sometimes
        - Rarely
    validations:
      required: true
