name: Bug report
description: Report a bug or regression
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is happening? Include what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps or a short repro snippet.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste any relevant logs, stack traces, or screenshots.
      render: shell
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: 0.1.0
    validations:
      required: true
  - type: input
    id: flutter
    attributes:
      label: Flutter version
      placeholder: "flutter --version"
    validations:
      required: true
  - type: dropdown
    id: reproducible
    attributes:
      label: Reproducibility
      options:
        - Always
        - Sometimes
        - Rarely
    validations:
      required: true
